# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: ubuntu-latest

variables:
- group: dev

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script:
    npm install
  displayName: 'Install dependencies'

- script:
    CI=true npm test
  displayName: 'Run tests'

- script:
    npm run build
  displayName: 'Build the project'

- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    sourceFolder: 'build' 
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    ArtifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Microsoft Azure'
    appType: 'webApp'
    appName: 'dev-appservice'
    package: '$(System.ArtifactsDirectory)/$(Build.BuildId).zip'
    deploymentMethod: 'auto'